### ISSUE TITLE
I've forked the repository and put instructions on how to build this on Ubuntu.

### ISSUE THREAD

**Issue by enjoysmath** [mailund/ziphmm#3]
Hello, I don't know if you're still here coding and maybe want to view some Ubuntu-or-related specific problem I had:

https://superuser.com/questions/1649422/how-can-i-get-passed-this-ziphmmlib-build-error-on-ubuntu/1649424#1649424

If so, let's discuss a way for me to work on this repository as a coder, or I could just keep developing on mine if that is the more appropriate route.  Thank you!

**Comment by mailund** [comment]
I'm not using the library anymore myself, but I'd be happy to add you as a developer if you want, or merge in a pull request

**Comment by enjoysmath** [comment]
> I'm not using the library anymore myself, but I'd be happy to add you as a developer if you want, or merge in a pull request

@mailund Could you take a look at my instructions.  I think the step:

```bash 
grep -rl lpthread ./ | xargs sed -i 's/lpthread/pthread/g`
```

Might be a little unnecessary if there is some more obvious way to change CXX_FLAGS that CMake sees (I don't know how it does) so that it reads `-pthread` instead of `-lpthread` in the flags line?

Also people on SO seem to say you want to prefer `-pthread` over `-lpthread` for various reasons.

**Comment by enjoysmath** [comment]
@mailund    I also changed over the code from Python 2 to Python 3 as it's important to support what the new user will have downloaded or should download.  I think it will still work for existing users if I put:

```python
from __future__ import print_function ```

At the top of each python file and also only conditionally call `filename.encode('utf-8')` in the interface functions that have file and our directory names and that are written in Python.  I think Python 2/ 3 handle the interpretation

**Comment by mailund** [comment]
I don't have access to any Ubuntu machines these days, nor Windows, so I cannot check the instructions myself, but one option for CXX_FLAGS is simply to set it conditionally in CMakeLists.txt, isn't it?

**Comment by enjoysmath** [comment]
> I don't have access to any Ubuntu machines these days, nor Windows, so I cannot check the instructions myself, but one option for CXX_FLAGS is simply to set it conditionally in CMakeLists.txt, isn't it?

I'm not sure how to create that conditional.  Specifically I don't know what to test for regarding "pthreads".  

See my pull request.
